namespace: logging

resources:
  - deploy.yml
  - rbac.yml
  - sm.yml

images:
  - name: quay.io/sighup/fluentd-elasticsearch
    newTag: v1.10.2-debian-1.0

configMapGenerator:
- name: fluentd-conf
  files:
    - fluent.conf
    - systemd.conf
    - kubernetes.conf
    - prometheus.conf
- name: fluentd-confd
  files:
    - nginx.conf=conf.d/nginx.conf
