apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          resources:
            limits:
              cpu: 2500m
              memory: 4G
            requests:
              cpu: 2000m
              memory: 3G

