apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curator
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            envFrom:
            - secretRef:
                name: curator-aws
