apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  template:
    spec:
      containers:
      - name: elasticsearch
        image: reg.sighup.io/elasticsearch-s3:0.1.0
        name: elasticsearch
