# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

namespace: logging

images:
  - name: docker.elastic.co/kibana/kibana
    newTag: 6.8.8

resources:
  - kibana.yml
