---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: curator-add-task
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: curator-add-task
rules:
  #  this will allow the list of a pod in a spefic namespace
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
  # this will allow this service account to create
  # a job based on a cronjob definition
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - create
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: curator-add-task
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: curator-add-task
subjects:
  - kind: ServiceAccount
    name: curator-add-task
